/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ImersaoRouteImport } from './routes/imersao'
import { Route as EscritorRouteImport } from './routes/escritor'
import { Route as AtuacaoRouteImport } from './routes/atuacao'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ImersaoRoute = ImersaoRouteImport.update({
  id: '/imersao',
  path: '/imersao',
  getParentRoute: () => rootRouteImport,
} as any)
const EscritorRoute = EscritorRouteImport.update({
  id: '/escritor',
  path: '/escritor',
  getParentRoute: () => rootRouteImport,
} as any)
const AtuacaoRoute = AtuacaoRouteImport.update({
  id: '/atuacao',
  path: '/atuacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atuacao': typeof AtuacaoRoute
  '/escritor': typeof EscritorRoute
  '/imersao': typeof ImersaoRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atuacao': typeof AtuacaoRoute
  '/escritor': typeof EscritorRoute
  '/imersao': typeof ImersaoRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atuacao': typeof AtuacaoRoute
  '/escritor': typeof EscritorRoute
  '/imersao': typeof ImersaoRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atuacao' | '/escritor' | '/imersao' | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atuacao' | '/escritor' | '/imersao' | '/sobre'
  id: '__root__' | '/' | '/atuacao' | '/escritor' | '/imersao' | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtuacaoRoute: typeof AtuacaoRoute
  EscritorRoute: typeof EscritorRoute
  ImersaoRoute: typeof ImersaoRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imersao': {
      id: '/imersao'
      path: '/imersao'
      fullPath: '/imersao'
      preLoaderRoute: typeof ImersaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escritor': {
      id: '/escritor'
      path: '/escritor'
      fullPath: '/escritor'
      preLoaderRoute: typeof EscritorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atuacao': {
      id: '/atuacao'
      path: '/atuacao'
      fullPath: '/atuacao'
      preLoaderRoute: typeof AtuacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtuacaoRoute: AtuacaoRoute,
  EscritorRoute: EscritorRoute,
  ImersaoRoute: ImersaoRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
